# Generated by Django 4.2.7 on 2024-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstones', '0004_gemstone_clarity'),
        ('profiles', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='gemstones',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='gemstone',
            field=models.ManyToManyField(to='gemstones.gemstone'),
        ),
    ]
