# Generated by Django 4.2.7 on 2024-06-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_wishlist_gemstones_wishlist_gemstone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='gemstone',
            new_name='gemstones',
        ),
    ]
