# Generated by Django 3.2.25 on 2024-04-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemstones', '0002_alter_gemstone_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemstone',
            name='rating',
        ),
    ]
