# Generated by Django 4.2.7 on 2024-06-09 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstones', '0004_gemstone_clarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 0, 0)),
        ),
    ]
