# Generated by Django 4.2.7 on 2024-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstones', '0006_alter_gemstone_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
