# Generated by Django 3.2.25 on 2024-05-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Frequently Asked Questions'},
        ),
    ]
